<a href="https://colab.research.google.com/github/GV2410/DWP-TECH-LAB/blob/main/Naive_Bayes21_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
import pandas as pd
import statsmodels.api as sm
#import gaussian Bayes model
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score # Changed prediction_score to precision_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
import warnings
warnings.filterwarnings('ignore')
import numpy as np

In [ ]:
# prompt: iris dataset

import pandas as pd
iris = datasets.load_iris()
X = pd.DataFrame(iris.data)
y = pd.DataFrame(iris.target)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("ROC_AUC score:",roc_auc_score(y_test,model.predict_proba(X_test),multi_class='ovr'))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Accuracy: 1.0
Confusion Matrix:
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
ROC_AUC score: 1.0


In [ ]:
iriss = datasets.load_iris()
iris = pd.DataFrame(iriss.data)
iris.colums = iriss.feature_names
iris['species'] = iriss.target
#Rename columns
iris.columns = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [ ]:
iris['species'].value_counts()


species
0    50
1    50
2    50
Name: count, dtype: int64

In [ ]:
#Distribution (mean) of independent columns respect to dependent column
iris.groupby('species').mean().round(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
species                                                           
0                     5.01              3.43               1.46   
1                     5.94              2.77               4.26   
2                     6.59              2.97               5.55   

         petal width (cm)  
species                    
0                    0.25  
1                    1.33  
2                    2.03

In [ ]:
#Information
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [ ]:
#Independent variables
X = iris.iloc[:,0:4]
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
#Dependent Variables
y = iris.iloc[:,4]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [ ]:
# prompt: split the dataset use model 1 by selecting the one variable create gaussian classifier and train the model using the training sets then mmodel prediction

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_auc_score

# Assuming 'iris' DataFrame is already loaded and preprocessed as in the provided code.

# Select only one variable (e.g., 'sepal length (cm)')
X = iris[['sepal length (cm)']]
y = iris['species']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Create and train the Gaussian Classifier
model = GaussianNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("ROC_AUC score:", roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr'))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85        16
           1       0.61      0.61      0.61        18
           2       0.60      0.55      0.57        11

    accuracy                           0.69        45
   macro avg       0.68      0.68      0.68        45
weighted avg       0.68      0.69      0.69        45

Accuracy: 0.6888888888888889
Confusion Matrix:
 [[14  2  0]
 [ 3 11  4]
 [ 0  5  6]]
ROC_AUC score: 0.8534493034671459


In [ ]:
# Instead of using 'dir.model.predict(X_test)', use the following:
model.predict(X_test)
pred = model.predict(X_test)

In [ ]:
pred=result.predict(X_test)
model_prediction=pd.DataFrame(pred.round(2),columns=['Prediction'])
print(model_prediction['Prediction'].head())


0    2
1    1
2    0
3    2
4    0
Name: Prediction, dtype: int64


In [ ]:
pred.round(2)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [ ]:
#split the dataset
#model 1
#start with selecting one variable
v1=iris[iris.columns[0:1]]
X_train,X_test,y_train,y_test=train_test_split(v1,y,test_size=0.3,random_state=21)

#create a gaussian classifier
model=GaussianNB()

#train the model using the training sets
result=model.fit(X_train,y_train)
result

#Model prediction
pred=result.predict(X_test)
model_prediction=pd.DataFrame(pred.round(2),columns=['Prediction'])
print(model_prediction['Prediction'].head())
#test set Target column Distribution
print(y_test.value_counts())
print(model_prediction['Prediction'].value_counts())

#predicted set Target column Distribution
# Convert pred to pandas Series to use value_counts()
print(pd.Series(pred).value_counts())
print(model_prediction['Prediction'].value_counts())


0    1
1    0
2    0
3    0
4    1
Name: Prediction, dtype: int64
species
1    16
2    15
0    14
Name: count, dtype: int64
Prediction
1    19
0    14
2    12
Name: count, dtype: int64
1    19
0    14
2    12
Name: count, dtype: int64
Prediction
1    19
0    14
2    12
Name: count, dtype: int64


In [ ]:
# prompt: lets take all 4 columns and get the accuracy

# Assuming 'iris' DataFrame is already loaded and preprocessed as in the provided code.

# Select all four variables
X = iris[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = iris['species']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=21)

# Create and train the Gaussian Classifier
model = GaussianNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("ROC_AUC score:", roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr'))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93        16
           2       0.88      1.00      0.94        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Accuracy: 0.9555555555555556
Confusion Matrix:
 [[14  0  0]
 [ 0 14  2]
 [ 0  0 15]]
ROC_AUC score: 0.9927043422733078
